<center>EDA_Shark_Tank_India</center>

In [77]:
import numpy as np
import pandas as pd
import matplotlib.pyplot as plt
import seaborn as sns

In [78]:
#Importing the Shark Tank India Dataset as df
df = pd.read_excel('EDA_Shark_Tank_India.xlsx')

In [79]:
#Displaying the first 5 rows of the dataset
df.head()

,episode_number,pitch_number,brand_name,idea,deal,pitcher_ask_amount,ask_equity,ask_valuation,deal_amount,deal_equity,...,ashneer_deal,anupam_deal,aman_deal,namita_deal,vineeta_deal,peyush_deal,ghazal_deal,total_sharks_invested,amount_per_shark,equity_per_shark
0,1,1,BluePine Industries,Frozen Momos,1,50.0,5.0,1000.00,75.0,16.00,...,1,0,1,0,1,0,0,3,25.0,5.333333
1,1,2,Booz scooters,Renting e-bike for mobility in private spaces,,40.0,15.0,266.67,40.0,50.00,...,1,0,0,0,1,0,0,2,20.0,25
2,1,3,Heart up my Sleeves,Detachable Sleeves,1,25.0,10.0,250.00,25.0,30.00,...,0,1,0,0,1,0,0,2,12.5,
3,2,4,Tagz Foods,Healthy Potato Chips,1,70.0,1.0,7000.00,70.0,2.75,...,1,0,0,0,0,0,0,1,70.0,2.75
4,2,5,Head and Heart,Brain Development Course,0,50.0,5.0,1000.00,0.0,0.00,...,0,0,0,0,0,0,0,0,0.0,0

In [80]:
#Checking the shape of the dataset
df.shape

(119, 28)

In [81]:
#Checking the columns of the dataset
df.columns

Index(['episode_number', 'pitch_number', 'brand_name', 'idea', 'deal',
       'pitcher_ask_amount', 'ask_equity', 'ask_valuation', 'deal_amount',
       'deal_equity', 'deal_valuation', 'ashneer_present', 'anupam_present',
       'aman_present', 'namita_present', 'vineeta_present', 'peyush_present',
       'ghazal_present', 'ashneer_deal', 'anupam_deal', 'aman_deal',
       'namita_deal', 'vineeta_deal', 'peyush_deal', 'ghazal_deal',
       'total_sharks_invested', 'amount_per_shark', 'equity_per_shark'],
      dtype='object')

In [82]:
#Checking the summary of the dataset
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 119 entries, 0 to 118
Data columns (total 28 columns):
 #   Column                 Non-Null Count  Dtype
---  ------                 --------------  -----
 0   episode_number         119 non-null    int64
 1   pitch_number           119 non-null    int64
 2   brand_name             119 non-null    object
 3   idea                   119 non-null    object
 4   deal                   119 non-null    object
 5   pitcher_ask_amount     119 non-null    float64
 6   ask_equity             119 non-null    float64
 7   ask_valuation          119 non-null    float64
 8   deal_amount            119 non-null    float64
 9   deal_equity            119 non-null    float64
 10  deal_valuation         119 non-null    float64
 11  ashneer_present        119 non-null    int64
 12  anupam_present         119 non-null    int64
 13  aman_present           119 non-null    int64
 14  namita_present         119 non-null    int64
 15  vineeta_present        119 non-null    int64
 16  peyush_present         119 non-null    int64
 17  ghazal_present         119 non-null    int64
 18  ashneer_deal           119 non-null    int64
 19  anupam_deal            119 non-null    int64
 20  aman_deal              119 non-null    int64
 21  namita_deal            119 non-null    int64
 22  vineeta_deal           119 non-null    int64
 23  peyush_deal            119 non-null    int64
 24  ghazal_deal            119 non-null    int64
 25  total_sharks_invested  119 non-null    int64
 26  amount_per_shark       119 non-null    float64
 27  equity_per_shark       119 non-null    object
dtypes: float64(7), int64(17), object(4)
memory usage: 26.2+ KB

In [83]:
#Checking the data types of the columns in the dataset
df.dtypes

episode_number             int64
pitch_number               int64
brand_name                object
idea                      object
deal                      object
pitcher_ask_amount       float64
ask_equity               float64
ask_valuation            float64
deal_amount              float64
deal_equity              float64
deal_valuation           float64
ashneer_present            int64
anupam_present             int64
aman_present               int64
namita_present             int64
vineeta_present            int64
peyush_present             int64
ghazal_present             int64
ashneer_deal               int64
anupam_deal                int64
aman_deal                  int64
namita_deal                int64
vineeta_deal               int64
peyush_deal                int64
ghazal_deal                int64
total_sharks_invested      int64
amount_per_shark         float64
equity_per_shark          object
dtype: object

In [84]:
#Checking the statistical summary of the dataset
df.describe()

,episode_number,pitch_number,pitcher_ask_amount,ask_equity,ask_valuation,deal_amount,deal_equity,deal_valuation,ashneer_present,anupam_present,...,ghazal_present,ashneer_deal,anupam_deal,aman_deal,namita_deal,vineeta_deal,peyush_deal,ghazal_deal,total_sharks_invested,amount_per_shark
count,119.000000,119.000000,119.000000,119.000000,119.000000,119.000000,119.000000,119.000000,119.000000,119.0,...,119.000000,119.000000,119.000000,119.000000,119.000000,119.000000,119.000000,119.000000,119.000000,119.000000
mean,18.655462,58.773109,315.529420,5.193277,3873.849664,32.495807,9.098571,480.963025,0.831933,1.0,...,0.226891,0.176471,0.210084,0.235294,0.184874,0.134454,0.235294,0.058824,1.235294,18.773112
std,10.145916,34.126990,2744.491665,3.903421,11848.205918,36.912136,13.145966,931.724822,0.375507,0.0,...,0.420592,0.382832,0.409091,0.425976,0.389837,0.342582,0.425976,0.236289,1.400399,24.569270
min,1.000000,1.000000,0.001010,0.250000,0.010000,0.000000,0.000000,0.000000,0.000000,1.0,...,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000
25%,10.000000,29.500000,42.500000,2.250000,645.835000,0.000000,0.000000,0.000000,1.000000,1.0,...,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000
50%,19.000000,59.000000,50.000000,5.000000,1250.000000,25.000000,3.000000,100.000000,1.000000,1.0,...,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,1.000000,10.000000
75%,27.000000,88.000000,80.000000,7.500000,2928.570000,50.000000,15.000000,500.000000,1.000000,1.0,...,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,2.000000,25.000000
max,35.000000,117.000000,30000.000000,25.000000,120000.000000,150.000000,75.000000,6666.670000,1.000000,1.0,...,1.000000,1.000000,1.000000,1.000000,1.000000,1.000000,1.000000,1.000000,5.000000,100.000000

In [85]:
#Checking the statistical summary of the categorical columns in the dataset
df.describe(include='object')

                 brand_name                idea  deal  equity_per_shark
count                   119                 119   119               119
unique                  117                 117     3                36
top     Heart up my Sleeves  Detachable Sleeves     1                 0
freq                      2                   2    65                51

In [86]:
#checking for missing values in the dataset
df.isnull().sum()

episode_number           0
pitch_number             0
brand_name               0
idea                     0
deal                     0
pitcher_ask_amount       0
ask_equity               0
ask_valuation            0
deal_amount              0
deal_equity              0
deal_valuation           0
ashneer_present          0
anupam_present           0
aman_present             0
namita_present           0
vineeta_present          0
peyush_present           0
ghazal_present           0
ashneer_deal             0
anupam_deal              0
aman_deal                0
namita_deal              0
vineeta_deal             0
peyush_deal              0
ghazal_deal              0
total_sharks_invested    0
amount_per_shark         0
equity_per_shark         0
dtype: int64

In [87]:
#Checking the duplicate values in the dataset
df.duplicated().sum()

np.int64(1)

In [88]:
#Checking the duplicate values and the duplicate rows in the dataset
df[df.duplicated(keep=False)]

,episode_number,pitch_number,brand_name,idea,deal,pitcher_ask_amount,ask_equity,ask_valuation,deal_amount,deal_equity,...,ashneer_deal,anupam_deal,aman_deal,namita_deal,vineeta_deal,peyush_deal,ghazal_deal,total_sharks_invested,amount_per_shark,equity_per_shark
88,27,88,Insurance Samadhan,Insurance Solutions,1,100.0,1.0,10000.0,100.0,4.0,...,0,0,0,0,0,1,0,1,100.0,4
89,27,88,Insurance Samadhan,Insurance Solutions,1,100.0,1.0,10000.0,100.0,4.0,...,0,0,0,0,0,1,0,1,100.0,4

In [89]:
#Deleting the duplicate rows in the dataset
df.drop_duplicates(inplace=True)

In [90]:
#Changing the dtype of column deal from object to int and equity_per_shark from object to float
df['deal'] = pd.to_numeric(df['deal'], errors='coerce').astype('Int64')
df['equity_per_shark'] = pd.to_numeric(df['equity_per_shark'], errors='coerce')

In [91]:
#Checking the dtypes again after changing the dtypes of the columns
df.dtypes

episode_number             int64
pitch_number               int64
brand_name                object
idea                      object
deal                       Int64
pitcher_ask_amount       float64
ask_equity               float64
ask_valuation            float64
deal_amount              float64
deal_equity              float64
deal_valuation           float64
ashneer_present            int64
anupam_present             int64
aman_present               int64
namita_present             int64
vineeta_present            int64
peyush_present             int64
ghazal_present             int64
ashneer_deal               int64
anupam_deal                int64
aman_deal                  int64
namita_deal                int64
vineeta_deal               int64
peyush_deal                int64
ghazal_deal                int64
total_sharks_invested      int64
amount_per_shark         float64
equity_per_shark         float64
dtype: object

In [92]:
#Checking for missing values again after changing the dtypes of the columns
df.isnull().sum()

episode_number           0
pitch_number             0
brand_name               0
idea                     0
deal                     2
pitcher_ask_amount       0
ask_equity               0
ask_valuation            0
deal_amount              0
deal_equity              0
deal_valuation           0
ashneer_present          0
anupam_present           0
aman_present             0
namita_present           0
vineeta_present          0
peyush_present           0
ghazal_present           0
ashneer_deal             0
anupam_deal              0
aman_deal                0
namita_deal              0
vineeta_deal             0
peyush_deal              0
ghazal_deal              0
total_sharks_invested    0
amount_per_shark         0
equity_per_shark         2
dtype: int64

In [93]:
#Checking the nulls values in the column deal and the corresponding values in the columns deal_amount and total_sharks_invested
df.loc[df['deal'].isnull(),['deal','deal_amount','total_sharks_invested',]]

    deal  deal_amount  total_sharks_invested
1   <NA>         40.0                      2
16  <NA>        100.0                      5

In [94]:
#imputing the null values in the column deal with 1 if there is deal_amount greater than 0 else 0
df['deal'] = df.apply(lambda x: 1 if x['deal_amount'] > 0 else 0, axis=1)

In [95]:
#Checking the null values in the column equity_per_shark and the corresponding values in the columns deal_equity and total_sharks_invested
df.loc[df['equity_per_shark'].isnull(),['equity_per_shark','deal_equity','total_sharks_invested',]]

    equity_per_shark  deal_equity  total_sharks_invested
2                NaN         30.0                      2
55               NaN          0.0                      0

In [96]:
#Imputing the null values in the column equity_per_shark with deal_equity divided by total_sharks_invested if total_sharks_invested is greater than 0 else 0
df['equity_per_shark'] = df.apply(lambda x: x['deal_equity']/x['total_sharks_invested'] if x['total_sharks_invested'] > 0 else 0, axis=1)

In [98]:
#Checking the null values again after doing some imputations
df.isnull().sum()

episode_number           0
pitch_number             0
brand_name               0
idea                     0
deal                     0
pitcher_ask_amount       0
ask_equity               0
ask_valuation            0
deal_amount              0
deal_equity              0
deal_valuation           0
ashneer_present          0
anupam_present           0
aman_present             0
namita_present           0
vineeta_present          0
peyush_present           0
ghazal_present           0
ashneer_deal             0
anupam_deal              0
aman_deal                0
namita_deal              0
vineeta_deal             0
peyush_deal              0
ghazal_deal              0
total_sharks_invested    0
amount_per_shark         0
equity_per_shark         0
dtype: int64

In [99]:
#Checking the deals that were successfully made and what percentage of the total pitches they constitute
successful_deals = df['deal'].sum()
total_pitches = df.shape[0]
percentage_successful = (successful_deals / total_pitches) * 100
print(f"Successful deals: {successful_deals}")
print(f"Total pitches: {total_pitches}")
print(f"Percentage of successful deals: {percentage_successful:.2f}%")

Successful deals: 66
Total pitches: 118
Percentage of successful deals: 55.93%

In [103]:
#Average and median deal amount for successful deals i.e. deal = 1
successful_deals_stats = df[df['deal'] == 1]['deal_amount'].agg(['mean', 'median'])
print(f"Average deal amount for successful deals: {successful_deals_stats['mean']:.2f}")
print(f"Median deal amount for successful deals: {successful_deals_stats['median']:.2f}")

Average deal amount for successful deals: 57.08
Median deal amount for successful deals: 50.00